module.exports = function buildGetPackage({}) {
        return function makeGetPackage({
        uid ,
        package_priority,
        name_th ,
        name_en ,
        description_th,
        description_en,
        package_saleprice ,
        package_regprice ,
        package_sale_start = 0,
        package_sale_end ,
        package_preservice_th ,
        package_postservice_th ,
        package_preservice_en ,
        package_postservice_en ,
        alert_message_th,
        alert_message_en,
        department_contact_th,
        department_contact_en,
        book_deadline,
        early_book,
        image,
        category,
        second_category,
        status = 'active',
        active_from ,
        active_to ,
    } = {}) {
        
        return Object.freeze({
            getUid : () => uid || null,
            getPackage_priority : () => package_priority|| null,
            getNameTH : () => name_th || null,
            getNameEN : () => name_en || null,
            getDescription_th :() => description_th|| null,
            getDescription_en :() => description_en|| null,
            getSalePrice :() => +package_saleprice || null,
            getRegPrice :() => +package_regprice || null,
            getSaleStart :() => package_sale_start || null,
            getSaleEnd :() => package_sale_end || null,
            getPreServiceTH :() => package_preservice_th || null,
            getPostServiceTH :() => package_postservice_th || null,
            getPreServiceEN :() => package_preservice_en || null,
            getPostServiceEN :() => package_postservice_en || null,
            getAlert_message_th :() => alert_message_th || null,
            getAlert_message_en :() => alert_message_en || null,
            getDepartmentContact_th:() => department_contact_th || null,
            getDepartmentContact_en:() => department_contact_en || null,
            getEarly_book :() => early_book || null,
            getBook_deadline :() => book_deadline || null,
            getImage : () => image || null,
            getCategory : () => category || null,
            getSecondCategory:() => second_category || null,
            getStatus :() => status || null,
            getActiveFrom :() => active_from || null,
            getActiveTO :() => active_to || null,
        })
    }
}

