module.exports = function buildGetPayment({}) {
        return function makeGetPayment({
            payment_no,
            order_id,
            cardToken,
            loyaltyPoints,
            merchantID,
            invoiceNo,
            cardNo,
            amount,
            monthlyPayment,
            currencyCode,
            recurringUniqueID,
            tranRef,
            referenceNo,
            approvalCode,
            eci,
            transactionDateTime,
            agentCode,
            channelCode,
            issuerCountry,
            issuerBank,
            cardType,
            idempotencyID,
            paymentScheme,
            respCode,
            respDesc,
            json_2c2p,

    } = {}) {
                
    
        return Object.freeze({
            getpayment_no: () =>  payment_no || null,
            getorder_id: () =>  order_id || null,
            getcardToken: () =>  cardToken || null,
            getloyaltyPoints: () =>  loyaltyPoints || null,
            getmerchantID: () =>  merchantID || null,
            getinvoiceNo: () =>  invoiceNo || null,
            getcardNo: () =>  cardNo || null,
            getamount: () =>  amount || null,
            getmonthlyPayment: () =>  monthlyPayment || null,
            getcurrencyCode: () =>  currencyCode || null,
            getrecurringUniqueID: () =>  recurringUniqueID || null,
            gettranRef: () =>  tranRef || null,
            getreferenceNo: () =>  referenceNo || null,
            getapprovalCode: () =>  approvalCode || null,
            geteci: () =>  eci || null,
            gettransactionDateTime: () =>  transactionDateTime || null,
            getagentCode: () =>  agentCode || null,
            getchannelCode: () =>  channelCode || null,
            getissuerCountry: () =>  issuerCountry || null,
            getissuerBank: () =>  issuerBank || null,
            getcardType: () =>  cardType || null,
            getidempotencyID: () =>  idempotencyID || null,
            getpaymentScheme: () =>  paymentScheme || null,
            getrespCode: () =>  respCode || null,
            getrespDesc: () =>  respDesc || null,
            getjson_2c2p: () =>  json_2c2p || null,
        })
    }
}

